CREATE TABLE cliente
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    telefone VARCHAR(16) NOT NULL,
    logradouro VARCHAR(40) NOT NULL,
    numero VARCHAR(5) NOT NULL,
    cidade VARCHAR(30) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    pais VARCHAR(10) NOT NULL,
    cep VARCHAR(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;